// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://laeaylctshzfnkxjrwye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhZWF5bGN0c2h6Zm5reGpyd3llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0Mjc0OTQsImV4cCI6MjA3NDAwMzQ5NH0.C7drnYOM9khQq5zDGK2wOPWNUNLh3imKbXCNSIRYaWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});